package emu.grasscutter.net.packet;

public final class PacketOpcodes {
    // Empty
    public static final int NONE = 219137; //oldVersion

    public static final int GetPlayerTokenReq = 29482;
    public static final int GetPlayerTokenRsp = 28793;
    public static final int PingReq = 9156;
    public static final int PingRsp = 8127;
    public static final int PlayerLoginReq = 9587;
    public static final int PlayerLoginRsp = 21573;
    public static final int PlayerEnterSceneNotify = 4230;
    public static final int EnterSceneReadyReq = 6522;
    public static final int EnterScenePeerNotify = 20519;
    public static final int EnterSceneReadyRsp = 21705;
    public static final int SceneInitFinishReq = 26987;
    public static final int PlayerEnterSceneInfoNotify = 8132;
    public static final int SceneInitFinishRsp = 1127;
    public static final int EnterSceneDoneReq = 7107;
    public static final int EnterSceneDoneRsp = 3324;
    public static final int PostEnterSceneReq = 7660;
    public static final int PostEnterSceneRsp = 298;
    public static final int GetSceneAreaReq = 28827;
    public static final int GetSceneAreaRsp = 21789;
    public static final int GetScenePointReq = 5843;
    public static final int GetScenePointRsp = 28915;
    public static final int SceneTeamUpdateNotify = 7041;
    public static final int AvatarDataNotify = 4171;
    public static final int SceneEntityAppearNotify = 27251;
    public static final int SceneEntityDisappearNotify = 25287;
    public static final int OpenStateUpdateNotify = 26532;
    public static final int AddQuestContentProgressReq = 569446; //oldVersion
    public static final int AddQuestContentProgressRsp = 358500; //oldVersion
    public static final int AvatarEquipChangeNotify = 22190;
    public static final int AvatarTeamUpdateNotify = 22864;
    public static final int ChangeAvatarReq = 7017;
    public static final int ChangeAvatarRsp = 6301;
    public static final int ClientAbilityChangeNotify = 6475;
    public static final int ClientAbilityInitFinishNotify = 1510;
    public static final int CombatInvocationsNotify = 8889;
    public static final int EntityFightPropChangeReasonNotify = 25708;
    public static final int EntityFightPropNotify = 9851;
    public static final int EntityFightPropUpdateNotify = 20481;
    public static final int EvtBeingHitNotify = 7121;
    public static final int EvtBeingHealedNotify = 829587; //oldVersion // no proto
    public static final int EvtBeingHitsCombineNotify = 2958;
    public static final int EvtCreateGadgetNotify = 7540;
    public static final int EvtDoSkillSuccNotify = 26003;
    public static final int FinishedParentQuestNotify = 743594; //oldVersion
    public static final int FinishedParentQuestUpdateNotify = 436394; //oldVersion
    public static final int GadgetInteractReq = 22231;
    public static final int GadgetInteractRsp = 26669;
    public static final int GetPlayerFriendListRsp = 23818;
    public static final int GetPlayerSocialDetailReq = 1165;
    public static final int GetPlayerSocialDetailRsp = 29969;
    public static final int HostPlayerNotify = 1525;
    public static final int LifeStateChangeNotify = 27502;
    public static final int MarkMapReq = 28697;
    public static final int NpcTalkReq = 1923;
    public static final int NpcTalkRsp = 23286;
    public static final int PlayerDataNotify = 25048;
    public static final int PlayerGameTimeNotify = 22544;
    public static final int PlayerSetPauseReq = 8695;
    public static final int PlayerSetPauseRsp = 749766; //oldVersion
    public static final int PlayerStoreNotify = 4274;
    public static final int PlayerWorldSceneInfoListNotify = 28813;
    public static final int PrivateChatNotify = 29521;
    public static final int PrivateChatReq = 8255;
    public static final int QuestDestroyNpcReq = 547023; //oldVersion
    public static final int QuestDestroyNpcRsp = 245975; //oldVersion
    public static final int QuestListNotify = 147673; //oldVersion
    public static final int QuestListUpdateNotify = 21700;
    public static final int QuestProgressUpdateNotify = 29083;
    public static final int SceneAreaWeatherNotify = 22674;
    public static final int SceneDataNotify = 1929;
    public static final int SceneTimeNotify = 9391;
    public static final int SceneTransToPointReq = 766;
    public static final int SceneTransToPointRsp = 21420;
    public static final int ServerTimeNotify = 24474;
    public static final int SetUpAvatarTeamReq = 25766;
    public static final int SetUpAvatarTeamRsp = 21081;
    public static final int StoreItemChangeNotify = 1830;
    public static final int StoreWeightLimitNotify = 20357;
    public static final int ToTheMoonEnterSceneReq = 6197;
    public static final int UnionCmdNotify = 21395;
    public static final int WearEquipReq = 24207;
    public static final int WearEquipRsp = 4288;
    public static final int WindSeedType1Notify = 24249;
    public static final int WorldDataNotify = 4552;
    public static final int EvtAvatarLockChairRsp = 7528;
    public static final int AvatarChangeCostumeRsp = 7006;
    public static final int EvtAvatarStandUpNotify = 9052;
    public static final int AvatarLifeStateChangeNotify = 27606;
    public static final int AvatarFlycloakChangeNotify = 9447;
    public static final int AvatarPropNotify = 4434;
    public static final int QuestTransmitRsp = 313650; //oldVersion
    public static final int PlayerTimeNotify = 8660;
    public static final int QuestUpdateQuestVarNotify = 178492; //oldVersion
    public static final int ServerGlobalValueChangeNotify = 26564;
    public static final int AvatarDieAnimationEndReq = 24530;
    public static final int AvatarDieAnimationEndRsp = 9076;
    public static final int SetNameCardReq = 5360;
    public static final int SetNameCardRsp = 643;
    public static final int PersonalSceneJumpReq = 29025;
    public static final int GetProfilePictureDataReq = 20692;
    public static final int GetProfilePictureDataRsp = 7323;
    public static final int GetAllUnlockNameCardReq = 29290;
    public static final int GetAllUnlockNameCardRsp = 534875; //oldVersion
    public static final int GetWidgetSlotRsp = 143708; //oldVersion
    public static final int GetParentQuestVideoKeyRsp = 629086; //oldVersion
    public static final int VehicleStaminaNotify = 7677;
    public static final int ServerBuffChangeNotify = 960867; //oldVersion // lazy
    public static final int VehicleInteractReq = 25703;
    public static final int VehicleInteractRsp = 2257;
    public static final int PlayerPropChangeNotify = 3321;
    public static final int PlayerPropChangeReasonNotify = 7099;
    public static final int PlayerPropNotify = 1883;
    public static final int AchievementAllDataNotify = 21255;
    public static final int GetActivityInfoReq = 414082; //oldVersion // list
    public static final int GetActivityInfoRsp = 428418; //oldVersion
    public static final int SetWidgetSlotReq = 9681;
    public static final int SetWidgetSlotRsp = 9741;
    public static final int ChangeGameTimeReq = 24164;
    public static final int ChangeGameTimeRsp = 561553; //oldVersion // stop
    public static final int WidgetSlotChangeNotify = 9782;
    public static final int UseItemReq = 29453;
    public static final int UseItemRsp = 26393;
    public static final int EvtAiSyncSkillCdNotify = 9593;
    public static final int WorktopOptionNotify = 188837; //oldVersion
    public static final int GadgetStateNotify = 2731;
    public static final int WorldPlayerDieNotify = 22060;
    public static final int WorldPlayerReviveReq = 4184;
    public static final int AvatarFetterDataNotify = 26072;
    public static final int ItemAddHintNotify = 8135;
    public static final int GetAreaExplorePointReq = 25511;
    public static final int GetAreaExplorePointRsp = 9845;
    public static final int ActivityScheduleInfoNotify = 21935;
    public static final int ActivityInfoNotify = 27105;
    public static final int GetGachaInfoReq = 27728;
    public static final int GetGachaInfoRsp = 2605;
    public static final int DoGachaReq = 2507;
    public static final int DoGachaRsp = 28960;
    public static final int AvatarChangeCostumeReq = 8555;
    public static final int AvatarWearFlycloakReq = 26329;
    public static final int AvatarWearFlycloakRsp = 25501;
    public static final int AvatarGainFlycloakNotify = 3806;
    public static final int AvatarChangeTraceEffectReq = 469467; //oldVersion
    public static final int EvtDestroyGadgetNotify = 25036;
    public static final int GetWidgetSlotReq = 866785; //oldVersion
    public static final int EvtAvatarLockChairReq = 21370;
    public static final int ObstacleModifyNotify = 2360;
    public static final int GetMapAreaReq = 250343; //oldVersion
    public static final int GetMapAreaRsp = 26444;
    public static final int EnterWorldAreaReq = 20065;
    public static final int EnterWorldAreaRsp = 3984;
    public static final int AbilityChangeNotify = 1848;
    public static final int SceneAreaUnlockNotify = 4575;
    public static final int ScenePointUnlockNotify = 525;
    public static final int AbilityInvocationsNotify = 7162;
    public static final int AvatarSkillUpgradeReq = 2526;
    public static final int AvatarSkillUpgradeRsp = 8619;
    public static final int SkipPlayerGameTimeRsp = 217;
    public static final int SkipPlayerGameTimeReq = 22456;
    public static final int AbilityInvocationFailNotify = 21619;
    public static final int AbilityInvocationFixedNotify = 883210; //oldVersion
    public static final int AchievementUpdateNotify = 22221;
    public static final int AddNoGachaAvatarCardNotify = 1660;
    public static final int AllWidgetDataNotify = 27274;
    public static final int AreaPlayInfoNotify = 262699; //oldVersion
    public static final int AvatarAddNotify = 3762;
    public static final int AvatarFetterLevelRewardReq = 29383;
    public static final int AvatarFetterLevelRewardRsp = 28192;
    public static final int AvatarFightPropNotify = 26714;
    public static final int AvatarFightPropUpdateNotify = 26534;
    public static final int AvatarPropChangeReasonNotify = 28442;
    public static final int AvatarSkillChangeNotify = 8587;
    public static final int AvatarSkillInfoNotify = 5979;
    public static final int AvatarSkillMaxChargeCountNotify = 2578;
    public static final int ClientAbilitiesInitFinishCombineNotify = 2819;
    public static final int ClientReconnectNotify = 700994; //oldVersion
    public static final int DoSetPlayerBornDataNotify = 995908; //oldVersion
    public static final int EntityAiSyncNotify = 22883;
    public static final int EntityTagChangeNotify = 186951; //oldVersion
    public static final int EvtAiSyncCombatThreatInfoNotify = 21191;
    public static final int EvtAvatarSitDownNotify = 4734;
    public static final int EvtEntityRenderersChangedNotify = 188;
    public static final int LevelTagDataNotify = 582226; //oldVersion
    public static final int ServerCondMeetQuestListUpdateNotify = 5694;
    public static final int ParentQuestInferenceDataNotify = 731736; //oldVersion
    public static final int PersonalSceneJumpRsp = 27632;
    public static final int QuestCreateEntityReq = 914018; //oldVersion
    public static final int QuestCreateEntityRsp = 608874; //oldVersion
    public static final int QuestDelNotify = 240240; //oldVersion
    public static final int QuestDestroyEntityReq = 651892; //oldVersion
    public static final int QuestDestroyEntityRsp = 336500; //oldVersion
    public static final int QuestGlobalVarNotify = 428662; //oldVersion
    public static final int QuestTransmitReq = 799353; //oldVersion
    public static final int QuestUpdateQuestTimeVarNotify = 729722; //oldVersion
    public static final int QuestUpdateQuestVarReq = 914048; //oldVersion
    public static final int QuestUpdateQuestVarRsp = 209544; //oldVersion
    public static final int QuickUseWidgetReq = 750217; //oldVersion
    public static final int QuickUseWidgetRsp = 252557; //oldVersion
    public static final int SceneEntityDrownReq = 27555;
    public static final int SceneForceLockNotify = 3686;
    public static final int SceneForceUnlockNotify = 27820;
    public static final int ServerDisconnectClientNotify = 26469;
    public static final int SetPlayerBornDataReq = 8910;
    public static final int SetPlayerBornDataRsp = 4259;
    public static final int SetUpLunchBoxWidgetReq = 2551;
    public static final int SetUpLunchBoxWidgetRsp = 783016; //oldVersion
    // 奶龙大王666
    public static final int AvatarChangeCostumeNotify = 29541;
    public static final int AvatarGainCostumeNotify = 848554; //oldVersion
    public static final int SetEntityClientDataNotify = 28695;
    public static final int AvatarSkillDepotChangeNotify = 590;
    public static final int ClientAIStateNotify = 932524; //oldVersion
    public static final int GetQuickswapWidgetsReq = 137902; //oldVersion
    public static final int SetPlayerPropReq = 559799; //oldVersion
    public static final int OpenStateChangeNotify = 2866;
    public static final int ScenePlayerLocationNotify = 565950; //oldVersion
    public static final int WorldPlayerLocationNotify = 625347; //oldVersion
    public static final int GetPlayerFriendListReq = 24834;
    public static final int GetPlayerBlacklistReq = 8057;
    public static final int GetPlayerAskFriendListReq = 27933;
    public static final int GetPlayerAskFriendListRsp = 26596;
    public static final int GetRecentMpPlayerListReq = 26317;
    public static final int PullPrivateChatReq = 27778;
    public static final int PullRecentChatReq = 3148;
    // PullPrivateChatRsp|PullRecentChatRsp 23999 or 4408
    public static final int PullPrivateChatRsp = 28658;
    public static final int PullRecentChatRsp = 27057;
    public static final int ReadPrivateChatReq = 979687; //oldVersion
    public static final int SetOpenStateReq = 7413;
    public static final int SetOpenStateRsp = 5961;
    // 进入传送点区域通知(C->S), 女神像传送点
    public static final int EnterTransPointRegionNotify = 283372; //oldVersion
    // 离开传送点区域通知(C->S), 女神像传送点
    public static final int ExitTransPointRegionNotify = 463598; //oldVersion
    public static final int CombineFormulaDataNotify = 705265; //oldVersion
    public static final int GetQuickswapWidgetsRsp = 148211; //oldVersion
    public static final int VehiclePhlogistonPointsNotify = 189171; //oldVersion
    public static final int WeaponAwakenReq = 8528;
    public static final int WeaponAwakenRsp = 20799;
    public static final int GetShopmallDataRsp = 25698;
    // 角色突破
    public static final int AvatarPromoteReq = 1249;
    public static final int AvatarPromoteRsp = 715534; //oldVersion   // 这玩意就算不对也能正常工作 所以这个可能是假的



    public static final int DungeonSettleNotify = 746256; //oldVersion //
    public static final int AntiAddictNotify = 26486;
    public static final int HitClientTrivialNotify = 482080; //oldVersion //
    public static final int StoreItemDelNotify = 2233;
    public static final int ClientScriptEventNotify = 543523; //oldVersion //
    public static final int PersonalLineAllDataRsp = 221992; //oldVersion //
    public static final int AskAddFriendRsp = 746283; //oldVersion //
    public static final int AvatarDelNotify = 701229; //oldVersion // //24313 or 27625
    public static final int WorldChestOpenNotify = 924463; //oldVersion //
    public static final int WidgetCoolDownNotify = 510768; //oldVersion //
    public static final int ForgeFormulaDataNotify = 473908; //oldVersion //
    public static final int ForgeStartReq = 385850; //oldVersion //
    public static final int ForgeStartRsp = 879422; //oldVersion // 单个retcode 不用核对cmdid
    public static final int AvatarSatiationDataNotify = 3220;
    public static final int BlossomBriefInfoNotify = 822085; //oldVersion //
    public static final int BuyGoodsReq = 365387; //oldVersion // // ShopGoods 的 proto 可能有问题
    public static final int BuyGoodsRsp = 598860; //oldVersion // // ShopGoods 的 proto 可能有问题
    public static final int BuyResinReq = 680780; //oldVersion // 等待抓取
    public static final int BuyResinRsp = 787278; //oldVersion //
    public static final int CardProductRewardNotify = 754508; //oldVersion //
    public static final int CombineReq = 471888; //oldVersion
    public static final int CombineRsp = 265037; //oldVersion
    public static final int TakeCompoundOutputReq = 449355; //oldVersion //
    public static final int TakeCompoundOutputRsp = 541523; //oldVersion //
    public static final int PlayerCompoundMaterialReq = 885588; //oldVersion //
    public static final int PlayerCompoundMaterialRsp = 920396; //oldVersion //
    public static final int CompoundDataNotify = 775001; //oldVersion //
    public static final int CoopDataNotify = 703322; //oldVersion //
    public static final int DelTeamEntityNotify = 568156; //oldVersion // // 29714 or 26259
    public static final int UpdateAbilityCreatedMovingPlatformNotify = 379744; //oldVersion //
    public static final int DropHintNotify = 901992; //oldVersion
    public static final int DungeonEntryToBeExploreNotify = 695149; //oldVersion // // 1436 or 21790
    public static final int DungeonRestartRsp = 287597; //oldVersion // // 2128 or 22307
    public static final int DungeonWayPointNotify = 375663; //oldVersion //
    public static final int EnterTrialAvatarActivityDungeonRsp = 256877; //oldVersion // // 244 or 1551
    public static final int EvtAvatarEnterFocusNotify = 201586; //oldVersion //
    public static final int EvtAvatarExitFocusNotify = 420724; //oldVersion // // 20290 or 8696
    public static final int EvtAvatarUpdateFocusNotify = 648053; //oldVersion // // 20290 or 8696
    public static final int ForgeDataNotify = 340854; //oldVersion //
    public static final int ForgeGetQueueDataRsp = 308087; //oldVersion //
    public static final int ForgeQueueDataNotify = 727927; //oldVersion //
    public static final int FurnitureMakeStartRsp = 273276; //oldVersion // // 29740 or 24667
    public static final int GachaWishReq = 174975; //oldVersion
    public static final int GachaWishRsp = 4512;
    public static final int GetAuthkeyReq = 314243; //oldVersion //
    public static final int GetAuthkeyRsp = 179078; //oldVersion //
    public static final int GetCompoundDataReq = 953224; //oldVersion // // 在例如打开烹饪界面时出现
    public static final int GetCompoundDataRsp = 740233; //oldVersion //
    public static final int GetDailyDungeonEntryInfoReq = 490377; //oldVersion // // 23858 or 26515
    public static final int GetDungeonEntryExploreConditionReq = 363406; //oldVersion // // 1436 or 21790
    public static final int GivingRecordNotify = 140177; //oldVersion //
    public static final int GmTalkRsp = 25410;
    public static final int GadgetAutoPickDropInfoNotify = 25444;
    public static final int ExecuteGadgetLuaReq = 840603; //oldVersion // // 解的proto字段有可能是错的
    public static final int ExecuteGadgetLuaRsp = 488346; //oldVersion // 单个retcode不用解
    public static final int LevelupCityReq = 529311; //oldVersion //
    public static final int LevelupCityRsp = 629671; //oldVersion //
    public static final int MassiveEntityElementOpBatchNotify = 2035;
    public static final int McoinExchangeHcoinReq = 392112; //oldVersion //
    public static final int McoinExchangeHcoinRsp = 408496; //oldVersion //
    public static final int MonsterAIConfigHashNotify = 242612; //oldVersion //
    public static final int MonsterAlertChangeNotify = 703412; //oldVersion //
    public static final int MonsterSummonTagNotify = 23390;
    public static final int MusicGameSettleReq = 259010; //oldVersion //
    public static final int MusicGameSettleRsp = 469959; //oldVersion // // 25598 or 6575
    public static final int MusicGameStartReq = 719818; //oldVersion // // 3045 or 20846
    public static final int MusicGameStartRsp = 713674; //oldVersion // // 27757 or 20172 or 28729
    public static final int PathfindingEnterSceneRsp = 816076; //oldVersion // 单个retcode不用解
    public static final int PlayerApplyEnterHomeNotify = 297933; //oldVersion // // 8132 or 38
    public static final int PlayerApplyEnterHomeResultNotify = 674766; //oldVersion //
    public static final int PlayerApplyEnterHomeResultReq = 216016; //oldVersion // // 378 or 1860
    public static final int PlayerApplyEnterHomeResultRsp = 699355; //oldVersion //
    public static final int ProudSkillChangeNotify = 28849;
    public static final int ProudSkillExtraLevelNotify = 916448; //oldVersion //
    public static final int ReceivedTrialAvatarActivityRewardReq = 351205; //oldVersion // // 5449 or 5667
    public static final int ReceivedTrialAvatarActivityRewardRsp = 463847; //oldVersion // // 244 or 1551
    public static final int ReliquaryDecomposeReq = 955372; //oldVersion //
    public static final int ReliquaryDecomposeRsp = 443375; //oldVersion //
    public static final int ReliquaryUpgradeReq = 23726;
    public static final int ReliquaryUpgradeRsp = 7501;
    public static final int SceneAudioNotify = 893940; //oldVersion //
    public static final int SceneEntityMoveNotify = 594937; //oldVersion // // 7026 or 22008
    public static final int SceneEntityUpdateNotify = 254970; //oldVersion // // 1936 or 6409
    public static final int ScenePlayerSoundNotify = 203771; //oldVersion //
    public static final int SceneWeatherForcastReq = 214012; //oldVersion //
    public static final int SetCoopChapterViewedRsp = 250880; //oldVersion // // 2246 or 29751 or 22019
    public static final int ShowCommonTipsNotify = 316418; //oldVersion //
    public static final int StartCoopPointReq = 615432; //oldVersion //
    public static final int StartCoopPointRsp = 416779; //oldVersion //
    public static final int TakeAchievementGoalRewardReq = 613389; //oldVersion // // 4455 or 24332
    public static final int TakeAchievementGoalRewardRsp = 347154; //oldVersion // // 26805 or 1595
    public static final int TakeAchievementRewardReq = 662546; //oldVersion // // 4455 or 24332
    public static final int TakeAchievementRewardRsp = 566295; //oldVersion // // 26805 or 1595
    public static final int TakeBattlePassMissionPointReq = 404503; //oldVersion //
    public static final int TakeBattlePassRewardReq = 844834; //oldVersion
    public static final int TakeBattlePassRewardRsp = 850983; //oldVersion
    public static final int TakeFurnitureMakeReq = 461864; //oldVersion //
    public static final int TakeFurnitureMakeRsp = 666663; //oldVersion //
    public static final int TakePlayerLevelRewardReq = 564266; //oldVersion
    public static final int TakePlayerLevelRewardRsp = 107562; //oldVersion
    public static final int UnlockNameCardNotify = 9355;
    public static final int UnlockPersonalLineReq = 216119; //oldVersion // // 2554 or 727
    public static final int UnlockPersonalLineRsp = 785463; //oldVersion //
    // 做饭
    public static final int PlayerCookArgsReq = 250936; //oldVersion //
    public static final int PlayerCookArgsRsp = 115771; //oldVersion // 主要字段没有特征 先不解
    public static final int PlayerCookReq = 982081; //oldVersion //
    public static final int PlayerCookRsp = 885826; //oldVersion //
    // 销毁材料
    public static final int DestroyMaterialReq = 422980; //oldVersion
    public static final int DestroyMaterialRsp = 306244; //oldVersion
    // 解锁命座
    public static final int UnlockAvatarTalentReq = 27021;
    public static final int UnlockAvatarTalentRsp = 910;
    // 房主踢人
    public static final int SceneKickPlayerReq = 24333;
    public static final int SceneKickPlayerRsp = 982102; //oldVersion // // 7966 or 20150 or 9301 or 24287 or 5497 or 21021 or 7700
    // 自己退房间
    public static final int PlayerGetForceQuitBanInfoReq = 3524;
    // 返回单人世界 作用未知
    public static final int BackMyWorldReq = 304230; //oldVersion // // 虚假的值
    public static final int BackMyWorldRsp = 926822; //oldVersion //
    // 客户端退出游戏
    public static final int PlayerForceExitReq = 29660;
    public static final int PlayerForceExitRsp = 982122; //oldVersion //
    // 切换配队
    public static final int ChooseCurAvatarTeamReq = 6643;
    public static final int ChooseCurAvatarTeamRsp = 482409; //oldVersion //
    // 添加配队容量
    public static final int AddBackupAvatarTeamReq = 377962; //oldVersion //
    public static final int AddBackupAvatarTeamRsp = 887918; //oldVersion //
    // 角色在秘境死亡
    public static final int DungeonPlayerDieReq = 218223; //oldVersion //
    public static final int DungeonPlayerDieRsp = 654450; //oldVersion //
    // 机关相关
    public static final int PlatformChangeRouteNotify = 773237; //oldVersion //
    public static final int PlatformStartRouteNotify = 715898; //oldVersion //
    public static final int PlatformStopRouteNotify = 707709; //oldVersion //
    // 可能是主角切换元素
    public static final int AvatarChangeElementTypeReq = 775297; //oldVersion
    public static final int AvatarChangeElementTypeRsp = 101505; //oldVersion // 单个retcode不用解
    // 联机配队
    public static final int ChangeMpTeamAvatarReq = 7723;
    public static final int ChangeMpTeamAvatarRsp = 1076;
    // 装备卸下
    public static final int TakeoffEquipReq = 1408;
    public static final int TakeoffEquipRsp = 5656;
    // 纪行
    public static final int SetBattlePassViewedReq = 162956; //oldVersion //
    public static final int SetBattlePassViewedRsp = 443558; //oldVersion // // 可能是 22048 533 26489 902 28919 9890 23101 21184 9036 目前实测都无效
    // 深渊
    public static final int TowerAllDataRsp = 1197;
    public static final int TowerCurLevelRecordChangeNotify = 703656; //oldVersion //
    public static final int EnterTrialAvatarActivityDungeonReq = 695465; //oldVersion //
    public static final int TowerEnterLevelReq = 887975; //oldVersion //
    public static final int TowerEnterLevelRsp = 902327; //oldVersion //
    public static final int TowerFloorRecordChangeNotify = 9617;
    public static final int TowerLevelStarCondNotify = 713919; //oldVersion //
    public static final int TowerTeamSelectReq = 363714; //oldVersion //
    public static final int TowerTeamSelectRsp = 595140; //oldVersion // 单个retcode不用解
    public static final int DungeonRestartReq = 201929; //oldVersion //
    // 神像对话
    public static final int GroupSuiteNotify = 9230;


    public static final int DelBackupAvatarTeamReq = 890059; //oldVersion //
    public static final int DelBackupAvatarTeamRsp = 998605; //oldVersion //
    public static final int AvatarTeamAllDataNotify = 25826;
    public static final int CutSceneBeginNotify = 853202; //oldVersion //
    public static final int DungeonEntryInfoReq = 21513;
    public static final int PathfindingEnterSceneReq = 2327;
    public static final int ScenePlayerInfoNotify = 8940;
    public static final int SyncScenePlayTeamEntityNotify = 28714;
    public static final int SyncTeamEntityNotify = 26522;
    public static final int PlayerQuitDungeonRsp = 330970; //oldVersion
    public static final int GetAllMailResultNotify = 8789;
    public static final int BattlePassAllDataNotify = 22686;
    public static final int TakeBattlePassMissionPointRsp = 406755; //oldVersion //
    public static final int EvtBulletHitNotify = 5682;
    public static final int BattlePassCurScheduleUpdateNotify = 6966;
    public static final int SceneEntityDrownRsp = 759020; //oldVersion //
    public static final int GetInvestigationMonsterRsp = 28174;
    public static final int SetPlayerNameReq = 5892;
    public static final int SetPlayerNameRsp = 28180;
    public static final int SetPlayerSignatureReq = 963826; //oldVersion
    public static final int SetPlayerSignatureRsp = 847094; //oldVersion
    public static final int SetPlayerHeadImageReq = 5505;
    public static final int SetPlayerHeadImageRsp = 27303;
    public static final int SetPlayerBirthdayReq = 27104;
    public static final int SetPlayerBirthdayRsp = 8769;
    public static final int AvatarExpeditionDataNotify = 621826; //oldVersion
    public static final int BattlePassMissionUpdateNotify = 6834;
    public static final int GetDailyDungeonEntryInfoRsp = 363781; //oldVersion //
    public static final int DealAddFriendRsp = 505;
    public static final int CodexDataUpdateNotify = 4606;
    public static final int ChapterStateNotify = 754956; //oldVersion //
    public static final int MarkMapRsp = 988431; //oldVersion //
    public static final int OtherPlayerEnterHomeNotify = 187664; //oldVersion //
    public static final int PlayerChatNotify = 2036;
    public static final int CreateVehicleReq = 474393; //oldVersion //
    public static final int CreateVehicleRsp = 689436; //oldVersion //
    public static final int DungeonEntryInfoRsp = 2148;
    public static final int PlayerEnterDungeonReq = 5926;
    public static final int PlayerEnterDungeonRsp = 179487; //oldVersion //
    public static final int PlayerQuitDungeonReq = 212262; //oldVersion
    public static final int SelectWorktopOptionReq = 9194;
    public static final int SelectWorktopOptionRsp = 20189;
    public static final int DungeonChallengeBeginNotify = 396594; //oldVersion //
    public static final int ChallengeDataNotify = 298291; //oldVersion //
    public static final int DungeonChallengeFinishNotify = 939320; //oldVersion //
    public static final int WorldPlayerReviveRsp = 406842; //oldVersion //
    public static final int GetFriendShowAvatarInfoRsp = 810299; //oldVersion //
    public static final int GetPlayerBlacklistRsp = 26799;
    public static final int UpdatePlayerShowAvatarListReq = 716094; //oldVersion //
    public static final int UpdatePlayerShowAvatarListRsp = 814400; //oldVersion //
    public static final int UpdatePlayerShowNameCardListReq = 136513; //oldVersion
    public static final int UpdatePlayerShowNameCardListRsp = 320836; //oldVersion
    public static final int WidgetDoBagReq = 468292; //oldVersion
    public static final int WidgetDoBagRsp = 691526; //oldVersion //
    public static final int WidgetGadgetDataNotify = 353607; //oldVersion //
    public static final int HomeChooseModuleReq = 595272; //oldVersion //
    public static final int HomeChooseModuleRsp = 443720; //oldVersion //
    public static final int TryEnterHomeReq = 728392; //oldVersion //
    public static final int TryEnterHomeRsp = 791883; //oldVersion //
    public static final int HomeBasicInfoNotify = 261453; //oldVersion //
    public static final int PlayerQuitFromHomeNotify = 599374; //oldVersion //
    public static final int HomeModuleSeenReq = 587092; //oldVersion
    public static final int HomeModuleSeenRsp = 867669; //oldVersion
    public static final int PlayerHomeCompInfoNotify = 671061; //oldVersion
    public static final int HomeComfortInfoNotify = 787799; //oldVersion //
    public static final int HomeModuleUnlockNotify = 757080; //oldVersion //
    public static final int FurnitureCurModuleArrangeCountNotify = 963930; //oldVersion //
    public static final int HomeMarkPointNotify = 183644; //oldVersion //
    public static final int HomeAllUnlockedBgmIdListNotify = 562526; //oldVersion //
    public static final int HomeAvatarAllFinishRewardNotify = 226664; //oldVersion //
    public static final int HomeGetBasicInfoReq = 771436; //oldVersion //
    public static final int HomePreChangeEditModeNotify = 875884; //oldVersion //
    public static final int HomeChangeEditModeReq = 693612; //oldVersion //
    public static final int HomeChangeEditModeRsp = 361842; //oldVersion //
    public static final int HomeEnterEditModeFinishReq = 873849; //oldVersion //
    public static final int HomeEnterEditModeFinishRsp = 732542; //oldVersion //
    public static final int HomeChangeBgmNotify = 525698; //oldVersion //
    public static final int HomeChangeBgmReq = 126339; //oldVersion //
    public static final int HomeGetArrangementInfoReq = 951685; //oldVersion //
    public static final int HomeGetArrangementInfoRsp = 718213; //oldVersion //
    public static final int HomeUpdateArrangementInfoRsp = 773513; //oldVersion //
    public static final int HomeUpdateArrangementInfoReq = 904592; //oldVersion //
    public static final int GetShopReq = 29344;
    public static final int GetShopRsp = 7718;
    public static final int PersonalLineAllDataReq = 753048; //oldVersion //
    public static final int CodexDataFullNotify = 24456;
    public static final int HomeAvatarSummonAllEventNotify = 740765; //oldVersion //
    public static final int HomeAvatarSummonEventReq = 832926; //oldVersion //
    public static final int HomeAvatarRewardEventNotify = 806304; //oldVersion //
    public static final int HomeAvatarTalkFinishInfoNotify = 210350; //oldVersion //
    public static final int HomeAvatarTalkRsp = 175535; //oldVersion //
    public static final int HomeSceneJumpReq = 564656; //oldVersion //
    public static final int HomeSceneJumpRsp = 622003; //oldVersion //
    public static final int HomeTransferReq = 435636; //oldVersion //
    public static final int GetInvestigationMonsterReq = 4908;
    public static final int GetHomeLevelUpRewardReq = 171449; //oldVersion // // proto
    public static final int HomeAvatarRewardEventGetReq = 423358; //oldVersion //
    public static final int HomeAvatarRewardEventGetRsp = 120266; //oldVersion //
    public static final int GetAllMailNotify = 23698;
    public static final int HomeAvatarCostumeChangeNotify = 749003; //oldVersion //
    public static final int PlayerApplyEnterMpResultNotify = 28782;
    public static final int PlayerApplyEnterMpNotify = 7292;
    public static final int PlayerApplyEnterMpReq = 3169;
    public static final int PlayerApplyEnterMpRsp = 27465;
    public static final int PlayerApplyEnterMpResultReq = 3195;
    public static final int AskAddFriendNotify = 400878; //oldVersion //
    public static final int AskAddFriendReq = 25573;
    public static final int DealAddFriendReq = 5792;
    public static final int GetFriendShowAvatarInfoReq = 933367; //oldVersion //
    public static final int GetFriendShowNameCardInfoRsp = 105977; //oldVersion
    public static final int SetFriendEnterHomeOptionReq = 560637; //oldVersion //
    public static final int GetOnlinePlayerListReq = 27508;
    public static final int GetOnlinePlayerListRsp = 146;
    public static final int GetShopmallDataReq = 8867;
    public static final int GetActivityShopSheetInfoReq = 892427; //oldVersion // // proto
    public static final int GetActivityShopSheetInfoRsp = 222733; //oldVersion // // proto
    public static final int ServerAnnounceNotify = 21475;
    public static final int GetWorldMpInfoReq = 8536;
    public static final int GetWorldMpInfoRsp = 460308; //oldVersion // // proto
    public static final int ResinChangeNotify = 25153;
    public static final int GetMailItemReq = 5802;
    public static final int GetMailItemRsp = 265753; //oldVersion
    public static final int MailChangeNotify = 21162;
    public static final int ReadMailNotify = 724507; //oldVersion //
    public static final int ChangeMailStarNotify = 640536; //oldVersion
    public static final int DelMailReq = 640541; //oldVersion //
    public static final int DelMailRsp = 495131; //oldVersion
    public static final int HitTreeNotify = 26321;
    public static final int TheaterLobbySceneJumpReq = 402983; //oldVersion // // code
    public static final int TheaterLobbySceneJumpRsp = 308776; //oldVersion // // code
    public static final int UnfreezeGroupLimitNotify = 519723; //oldVersion //
    public static final int QueryCodexMonsterBeKilledNumReq = 21802;
    public static final int QueryCodexMonsterBeKilledNumRsp = 28995;
    public static final int GetRegionSearchReq = 958001; //oldVersion //
    public static final int PlayerChatReq = 21030;
    public static final int TowerAllDataReq = 24262;
    public static final int GetPlayerHomeCompInfoReq = 179771; //oldVersion //
    public static final int GetFurnitureCurModuleArrangeCountReq = 343612; //oldVersion //
    public static final int FurnitureMakeReq = 933446; //oldVersion //
    public static final int DungeonPlayerDieNotify = 23956;
    public static final int DungeonDieOptionReq = 853586; //oldVersion
    public static final int DungeonDieOptionRsp = 929371; //oldVersion
    public static final int ChangeTeamNameReq = 513;
    public static final int ChangeTeamNameRsp = 292456; //oldVersion
    public static final int WorldPlayerRTTNotify = 892521; //oldVersion
    public static final int PlayerApplyEnterMpResultRsp = 22181;
    public static final int PlayerGetForceQuitBanInfoRsp = 939631; //oldVersion
    public static final int PlayerPreEnterMpNotify = 28494;
    public static final int WorldPlayerInfoNotify = 9341;
    public static final int WeaponPromoteReq = 204415; //oldVersion
    public static final int WeaponPromoteRsp = 190087; //oldVersion
    public static final int WeaponUpgradeReq = 6683;
    public static final int WeaponUpgradeRsp = 7759;
    public static final int CalcWeaponUpgradeReturnItemsReq = 210580; //oldVersion //
    public static final int CalcWeaponUpgradeReturnItemsRsp = 968344; //oldVersion //
    public static final int SetEquipLockStateReq = 976543; //oldVersion //
    public static final int SetEquipLockStateRsp = 104098; //oldVersion //
    public static final int AvatarUpgradeReq = 5448;
    public static final int AvatarUpgradeRsp = 5088;
    public static final int AvatarUnlockTalentNotify = 4915;
    public static final int HomeAvatarTalkReq = 124591; //oldVersion //
    public static final int GetQuestLackingResourceRsp = 333488; //oldVersion //
    public static final int QueryPathReq = 2319;
    public static final int QueryPathRsp = 2375;
    public static final int UnlockTransPointReq = 29817;
    public static final int UnlockTransPointRsp = 698043; //oldVersion //


    // Packet Names
    public static final int PlayerEnterChildMapLayerNotify = 945851; //oldVersion // 没有作用
    public static final int PlayerEnterMapLayerNotify = 714432; //oldVersion // 没有作用
    public static final int ServerAnnounceRevokeNotify = 618176; //oldVersion // 没有作用
    public static final int PlayerChatRsp = 425671; //oldVersion // 可以忽略
    public static final int FurnitureMakeRsp = 726727; //oldVersion //

    public static final int ActivityTakeWatcherRewardReq = 745163; //oldVersion
    public static final int ActivityTakeWatcherRewardRsp = 323278; //oldVersion
    public static final int ActivityUpdateWatcherNotify = 509649; //oldVersion
    // 可能是角色派遣
    public static final int AvatarExpeditionAllDataReq = 585429; //oldVersion //
    public static final int AvatarExpeditionAllDataRsp = 906965; //oldVersion
    public static final int AvatarExpeditionCallBackReq = 952026; //oldVersion //
    public static final int AvatarExpeditionCallBackRsp = 349917; //oldVersion //
    public static final int AvatarExpeditionGetRewardReq = 677599; //oldVersion //
    public static final int AvatarExpeditionGetRewardRsp = 534239; //oldVersion //
    public static final int AvatarExpeditionStartReq = 945891; //oldVersion //
    public static final int AvatarExpeditionStartRsp = 270052; //oldVersion //

    public static final int BargainOfferPriceReq = 775909; //oldVersion //
    public static final int BargainOfferPriceRsp = 923369; //oldVersion //
    public static final int BargainStartNotify = 644842; //oldVersion //
    public static final int BargainTerminateNotify = 851691; //oldVersion //
    public static final int BeginCameraSceneLookNotify = 2745;
    public static final int BuyBattlePassLevelReq = 868083; //oldVersion //  可能纪行有关
    public static final int BuyBattlePassLevelRsp = 175862; //oldVersion //

    public static final int CanUseSkillNotify = 163583; //oldVersion // 不好解
    public static final int CancelCoopTaskReq = 360198; //oldVersion // 未实现的数据包
    //  上面的可以不解
    public static final int CheckUgcStateReq = 626440; //oldVersion //
    public static final int CheckUgcStateRsp = 478987; //oldVersion //
    public static final int CheckUgcUpdateReq = 126740; //oldVersion //
    public static final int CheckUgcUpdateRsp = 524052; //oldVersion //
    public static final int ClientLockGameTimeNotify = 999190; //oldVersion // 我觉得不用解
    public static final int CloseCommonTipsNotify = 757527; //oldVersion // 不好解
    public static final int CombineDataNotify = 651035; //oldVersion // 不好解

    public static final int CookDataNotify = 102176; //oldVersion //
    public static final int CookRecipeDataNotify = 397096; //oldVersion //

    public static final int DeleteFriendNotify = 964393; //oldVersion // 等待抓取
    public static final int DeleteFriendReq = 739114; //oldVersion //
    public static final int DeleteFriendRsp = 767785; //oldVersion //

    public static final int DungeonShowReminderNotify = 751400; //oldVersion // 不好解
    public static final int DungeonSlipRevivePointActivateReq = 735023; //oldVersion // 不好解
    public static final int DungeonSlipRevivePointActivateRsp = 288560; //oldVersion // 不好解
    public static final int DungeonWayPointActivateReq = 415539; //oldVersion // 不好解
    public static final int DungeonWayPointActivateRsp = 864053; //oldVersion // 不好解

    public static final int EndCameraSceneLookNotify = 517942; //oldVersion // 等待抓取

    public static final int EntityAiKillSelfNotify = 347962; //oldVersion // 不好解

    public static final int EvtBulletDeactiveNotify = 243519; //oldVersion // 懒得解了反正解不解都没事
    public static final int EvtBulletMoveNotify = 149318; //oldVersion // 懒得解了反正解不解都没事

    public static final int FireworksLaunchDataNotify = 696136; //oldVersion // 套娃太多了
    public static final int FireworksReformDataNotify = 902987; //oldVersion // 套娃太多了

    public static final int ForgeGetQueueDataReq = 175949; //oldVersion // 等待抓取
    public static final int ForgeQueueManipulateReq = 20468;
    public static final int ForgeQueueManipulateRsp = 29653;

    public static final int FurnitureMakeStartReq = 759632; //oldVersion //

    public static final int GetAllActivatedBargainDataReq = 495441; //oldVersion // 等待抓取
    public static final int GetAllActivatedBargainDataRsp = 300880; //oldVersion //

    public static final int GetAllH5ActivityInfoReq = 374617; //oldVersion // 等待抓取

    public static final int GetBargainDataReq = 812896; //oldVersion // 不好解
    public static final int GetBargainDataRsp = 417632; //oldVersion //

    public static final int GetChatEmojiCollectionReq = 700258; //oldVersion // 等待抓取
    public static final int GetChatEmojiCollectionRsp = 900964; //oldVersion // 不好解

    public static final int GetDungeonEntryExploreConditionRsp = 857956; //oldVersion // 不好解
    public static final int GetFriendShowNameCardInfoReq = 986983; //oldVersion // 等待抓取
    public static final int GetHomeLevelUpRewardRsp = 974701; //oldVersion // 不好解
    public static final int GetUgcBriefInfoReq = 135025; //oldVersion // 跳过
    public static final int GetUgcBriefInfoRsp = 845682; //oldVersion // 跳过
    public static final int GetUgcReq = 644978; //oldVersion //
    public static final int GetUgcRsp = 526196; //oldVersion //

    public static final int GmTalkReq = 192375; //oldVersion // 等待抓取
    public static final int GroupUnloadNotify = 683897; //oldVersion // 不好解
    public static final int H5ActivityIdsNotify = 137082; //oldVersion // 等待抓取

    // 家园
    public static final int HomeAvatarSummonEventRsp = 903042; //oldVersion //
    public static final int HomeAvatarSummonFinishReq = 538506; //oldVersion //
    public static final int HomeAvatarSummonFinishRsp = 849803; //oldVersion //
    public static final int HomeChangeBgmRsp = 858000; //oldVersion //
    public static final int HomeChangeModuleReq = 909202; //oldVersion //
    public static final int HomeChangeModuleRsp = 651158; //oldVersion //
    public static final int HomeGetOnlineStatusReq = 835484; //oldVersion //
    public static final int HomeGetOnlineStatusRsp = 882591; //oldVersion
    public static final int HomeKickPlayerReq = 501675; //oldVersion //
    public static final int HomeKickPlayerRsp = 886699; //oldVersion //
    public static final int HomeNewUnlockedBgmIdListNotify = 722861; //oldVersion //
    public static final int HomeResourceNotify = 503728; //oldVersion //
    public static final int HomeResourceTakeFetterExpReq = 767922; //oldVersion //
    public static final int HomeResourceTakeFetterExpRsp = 845757; //oldVersion //
    public static final int HomeResourceTakeHomeCoinReq = 473024; //oldVersion //
    public static final int HomeResourceTakeHomeCoinRsp = 640961; //oldVersion //
    public static final int HomeSaveArrangementNoChangeReq = 657347; //oldVersion //
    public static final int HomeSaveArrangementNoChangeRsp = 333763; //oldVersion //
    public static final int HomeSceneInitFinishReq = 946117; //oldVersion //
    public static final int HomeSceneInitFinishRsp = 538566; //oldVersion //
    public static final int HomeTransferRsp = 733127; //oldVersion //

    // 好像用不到这俩了
    public static final int ItemGivingReq = 604103; //oldVersion //
    public static final int ItemGivingRsp = 143305; //oldVersion //

    public static final int LaunchFireworksReq = 210888; //oldVersion // 不好解
    public static final int LaunchFireworksRsp = 268235; //oldVersion // 单个retcode 不用解

    public static final int MarkNewNotify = 509907; //oldVersion // 不好解
    public static final int MonsterForceAlertNotify = 366552; //oldVersion // 不好解
    public static final int PlayerLevelRewardUpdateNotify = 344026; //oldVersion // 不好解
    public static final int ReformFireworksReq = 528351; //oldVersion // 太麻烦了 先不搞
    public static final int ReformFireworksRsp = 956388; //oldVersion // 单个retcode 不用解
    public static final int SetChatEmojiCollectionReq = 718821; //oldVersion // 不好解 而且看起来没什么用 跳过
    public static final int SetChatEmojiCollectionRsp = 774123; //oldVersion // 单个retcode不用解

    public static final int SetFriendEnterHomeOptionRsp = 616428; //oldVersion // 单个retcode 不用解
    public static final int SetPlayerPropRsp = 563182; //oldVersion // 单个retcode不用解

    public static final int ShowClientGuideNotify = 554993; //oldVersion // 不好解
    public static final int TowerMiddleLevelChangeTeamNotify = 360435; //oldVersion // 待抓取
    public static final int UnlockedFurnitureFormulaDataNotify = 395253; //oldVersion // 不好解
    public static final int UnlockedFurnitureSuiteDataNotify = 346104; //oldVersion // 不好解
}
