package emu.grasscutter.tools;

public class unknownCmdId {
    public static final int SceneEntityDisappearNotify = 630785; //oldVersion
    public static final int AvatarAddNotify = 305153; //oldVersion
    public static final int AvatarPromoteReq = 729092; //oldVersion
    public static final int AvatarPromoteRsp = 194567; //oldVersion    // test
    public static final int EntityAiSyncNotify = 421899; //oldVersion
    public static final int DungeonSettleNotify = 495629; //oldVersion
    public static final int AntiAddictNotify = 333837; //oldVersion
    public static final int HitClientTrivialNotify = 309263; //oldVersion
    public static final int EvtAiSyncCombatThreatInfoNotify = 409615; //oldVersion
    public static final int AvatarFightPropUpdateNotify = 661519; //oldVersion
    public static final int AvatarFightPropNotify = 303118; //oldVersion
    public static final int EnterTransPointRegionNotify = 772110; //oldVersion
    public static final int ExitTransPointRegionNotify = 358423; //oldVersion
    public static final int EvtEntityRenderersChangedNotify = 188447; //oldVersion
    public static final int AddNoGachaAvatarCardNotify = 458789; //oldVersion // 非抽卡途径获得角色
    public static final int StoreItemDelNotify = 557096; //oldVersion // 最后一个命座解锁时扣除命星
    public static final int ClientAbilitiesInitFinishCombineNotify = 413738; //oldVersion
    public static final int ClientScriptEventNotify = 135214; //oldVersion
    public static final int PersonalLineAllDataRsp = 925752; //oldVersion
    public static final int AchievementUpdateNotify = 784442; //oldVersion // 成就
    public static final int AskAddFriendRsp = 872507; //oldVersion
    public static final int AvatarDelNotify = 708668; //oldVersion //24313 or 27625
    public static final int AvatarFetterLevelRewardReq = 761919; //oldVersion
    public static final int AvatarFetterLevelRewardRsp = 499778; //oldVersion
    public static final int WorldChestOpenNotify = 479299; //oldVersion
    public static final int WidgetCoolDownNotify = 761928; //oldVersion
    public static final int ForgeFormulaDataNotify = 991308; //oldVersion
    public static final int ForgeStartReq = 149582; //oldVersion
    public static final int ForgeStartRsp = 391246; //oldVersion 单个retcode 不用核对cmdid
    public static final int AvatarSatiationDataNotify = 594000; //oldVersion
    public static final int BlossomBriefInfoNotify = 165967; //oldVersion
    public static final int AvatarSkillChangeNotify = 309336; //oldVersion
    public static final int AvatarSkillDepotChangeNotify = 192601; //oldVersion
    public static final int AvatarSkillInfoNotify = 381020; //oldVersion
    public static final int AvatarSkillMaxChargeCountNotify = 929886; //oldVersion
    public static final int GetShopmallDataRsp = 182369; //oldVersion
    public static final int BuyGoodsReq = 897134; //oldVersion // ShopGoods 的 proto 可能有问题
    public static final int BuyGoodsRsp = 317554; //oldVersion // ShopGoods 的 proto 可能有问题
    public static final int BuyResinReq = 587897; //oldVersion 等待抓取
    public static final int BuyResinRsp = 346235; //oldVersion
    public static final int CombineFormulaDataNotify = 540796; //oldVersion
    public static final int CardProductRewardNotify = 790652; //oldVersion
    public static final int CombineReq = 454785; //oldVersion
    public static final int CombineRsp = 555144; //oldVersion // proto 字段可能有部分解错了
    public static final int TakeCompoundOutputReq = 835722; //oldVersion
    public static final int TakeCompoundOutputRsp = 966798; //oldVersion
    public static final int PlayerCompoundMaterialReq = 446609; //oldVersion
    public static final int PlayerCompoundMaterialRsp = 100502; //oldVersion
    public static final int CompoundDataNotify = 581785; //oldVersion
    public static final int CoopDataNotify = 729241; //oldVersion
    public static final int DelTeamEntityNotify = 364699; //oldVersion // 29714 or 26259
    public static final int UpdateAbilityCreatedMovingPlatformNotify = 114845; //oldVersion
    public static final int DropHintNotify = 471202; //oldVersion
    public static final int DungeonEntryToBeExploreNotify = 200867; //oldVersion // 1436 or 21790
    public static final int DungeonRestartRsp = 952485; //oldVersion // 2128 or 22307
    public static final int DungeonWayPointNotify = 352423; //oldVersion
    public static final int EnterTrialAvatarActivityDungeonRsp = 882858; //oldVersion // 244 or 1551
    public static final int EvtAvatarEnterFocusNotify = 561323; //oldVersion
    public static final int EvtAvatarExitFocusNotify = 821423; //oldVersion // 20290 or 8696
    public static final int EvtAvatarSitDownNotify = 813235; //oldVersion
    public static final int EvtAvatarUpdateFocusNotify = 458933; //oldVersion // 20290 or 8696
    public static final int ForgeDataNotify = 925878; //oldVersion
    public static final int ForgeGetQueueDataRsp = 344248; //oldVersion
    public static final int ForgeQueueDataNotify = 786617; //oldVersion
    public static final int FurnitureMakeStartRsp = 878778; //oldVersion // 29740 or 24667
    public static final int GachaWishReq = 567488; //oldVersion
    public static final int GachaWishRsp = 925889; //oldVersion
    public static final int GetAuthkeyReq = 381121; //oldVersion
    public static final int GetAuthkeyRsp = 432323; //oldVersion
    public static final int GetCompoundDataReq = 352452; //oldVersion // 在例如打开烹饪界面时出现
    public static final int GetCompoundDataRsp = 235719; //oldVersion
    public static final int GetDailyDungeonEntryInfoReq = 108748; //oldVersion // 23858 or 26515
    public static final int GetDungeonEntryExploreConditionReq = 735446; //oldVersion // 1436 or 21790
    public static final int GivingRecordNotify = 360663; //oldVersion
    public static final int GmTalkRsp = 313562; //oldVersion
    public static final int GadgetAutoPickDropInfoNotify = 301274; //oldVersion
    public static final int ExecuteGadgetLuaReq = 170205; //oldVersion // 解的proto字段有可能是错的
    public static final int ExecuteGadgetLuaRsp = 377057; //oldVersion 单个retcode不用解
    public static final int LevelupCityReq = 194795; //oldVersion
    public static final int LevelupCityRsp = 293100; //oldVersion
    public static final int MassiveEntityElementOpBatchNotify = 925935; //oldVersion
    public static final int McoinExchangeHcoinReq = 549107; //oldVersion
    public static final int McoinExchangeHcoinRsp = 817397; //oldVersion
    public static final int MonsterAIConfigHashNotify = 108799; //oldVersion
    public static final int MonsterAlertChangeNotify = 880897; //oldVersion
    public static final int MonsterSummonTagNotify = 356612; //oldVersion
    public static final int MusicGameSettleReq = 477445; //oldVersion
    public static final int MusicGameSettleRsp = 983302; //oldVersion // 25598 or 6575
    public static final int MusicGameStartReq = 663818; //oldVersion // 3045 or 20846
    public static final int MusicGameStartRsp = 604427; //oldVersion // 27757 or 20172 or 28729
    public static final int PathfindingEnterSceneRsp = 968972; //oldVersion 单个retcode不用解
    public static final int PersonalSceneJumpRsp = 348433; //oldVersion
    public static final int PlayerApplyEnterHomeNotify = 194840; //oldVersion // 8132 or 38
    public static final int PlayerApplyEnterHomeResultNotify = 508185; //oldVersion
    public static final int PlayerApplyEnterHomeResultReq = 835866; //oldVersion // 378 or 1860
    public static final int PlayerApplyEnterHomeResultRsp = 825630; //oldVersion
    public static final int ProudSkillChangeNotify = 958752; //oldVersion
    public static final int ProudSkillExtraLevelNotify = 813347; //oldVersion
    public static final int QuestDelNotify = 743718; //oldVersion
    public static final int QuestDestroyEntityReq = 905515; //oldVersion
    public static final int QuestDestroyEntityRsp = 999723; //oldVersion
    public static final int QuestGlobalVarNotify = 170296; //oldVersion
    public static final int QuestUpdateQuestVarReq = 223546; //oldVersion
    public static final int QuestUpdateQuestVarRsp = 205117; //oldVersion
    public static final int ReceivedTrialAvatarActivityRewardReq = 407874; //oldVersion // 5449 or 5667
    public static final int ReceivedTrialAvatarActivityRewardRsp = 659780; //oldVersion // 244 or 1551
    public static final int ReliquaryDecomposeReq = 104780; //oldVersion
    public static final int ReliquaryDecomposeRsp = 762189; //oldVersion
    public static final int ReliquaryUpgradeReq = 366925; //oldVersion
    public static final int ReliquaryUpgradeRsp = 655697; //oldVersion
    public static final int SceneAudioNotify = 608593; //oldVersion
    public static final int SceneEntityMoveNotify = 387410; //oldVersion // 7026 or 22008
    public static final int SceneEntityUpdateNotify = 454993; //oldVersion // 1936 or 6409
    public static final int ScenePlayerSoundNotify = 551252; //oldVersion
    public static final int SceneWeatherForcastReq = 180592; //oldVersion
    public static final int ServerDisconnectClientNotify = 950640; //oldVersion
    public static final int SetCoopChapterViewedRsp = 526708; //oldVersion // 2246 or 29751 or 22019
    public static final int SetPlayerBornDataReq = 459124; //oldVersion
    public static final int ShowCommonTipsNotify = 356724; //oldVersion
    public static final int StartCoopPointReq = 313719; //oldVersion
    public static final int StartCoopPointRsp = 936315; //oldVersion
    public static final int TakeAchievementGoalRewardReq = 153983; //oldVersion // 4455 or 24332
    public static final int TakeAchievementGoalRewardRsp = 362879; //oldVersion // 26805 or 1595
    public static final int TakeAchievementRewardReq = 381313; //oldVersion // 4455 or 24332
    public static final int TakeAchievementRewardRsp = 905601; //oldVersion // 26805 or 1595
    public static final int TakeBattlePassMissionPointReq = 659842; //oldVersion
    public static final int TakeBattlePassRewardReq = 219527; //oldVersion
    public static final int TakeBattlePassRewardRsp = 565641; //oldVersion
    public static final int TakeFurnitureMakeReq = 309641; //oldVersion
    public static final int TakeFurnitureMakeRsp = 622988; //oldVersion
    public static final int TakePlayerLevelRewardReq = 174477; //oldVersion
    public static final int TakePlayerLevelRewardRsp = 973199; //oldVersion
    public static final int UnlockNameCardNotify = 430479; //oldVersion
    public static final int UnlockPersonalLineReq = 792977; //oldVersion // 2554 or 727
    public static final int UnlockPersonalLineRsp = 174482; //oldVersion
    public static final int DoSetPlayerBornDataNotify = 235923; //oldVersion
    public static final int SetPlayerBornDataRsp = 643471; //oldVersion
    // 做饭
    public static final int PlayerCookArgsReq = 752023; //oldVersion
    public static final int PlayerCookArgsRsp = 272794; //oldVersion 主要字段没有特征 先不解
    public static final int PlayerCookReq = 919964; //oldVersion
    public static final int PlayerCookRsp = 283037; //oldVersion
    // 销毁材料
    public static final int DestroyMaterialReq = 283038; //oldVersion
    public static final int DestroyMaterialRsp = 317857; //oldVersion
    // 解锁命座
    public static final int UnlockAvatarTalentReq = 194995; //oldVersion
    public static final int UnlockAvatarTalentRsp = 176566; //oldVersion
    // 房主踢人
    public static final int SceneKickPlayerReq = 768441; //oldVersion
    public static final int SceneKickPlayerRsp = 790969; //oldVersion // 7966 or 20150 or 9301 or 24287 or 5497 or 21021 or 7700
    // 自己退房间
    public static final int PlayerGetForceQuitBanInfoReq = 430522; //oldVersion
    // 任务创建的实体 例如风魔龙的眼泪
    public static final int QuestCreateEntityReq = 125372; //oldVersion
    public static final int QuestCreateEntityRsp = 473533; //oldVersion
    // 返回单人世界 作用未知
    public static final int BackMyWorldReq = 754114; //oldVersion // 虚假的值 todo
    public static final int BackMyWorldRsp = 502210; //oldVersion
    // 任务传送
    public static final int QuestTransmitReq = 496069; //oldVersion
    public static final int QuestTransmitRsp = 494023; //oldVersion
    // 客户端退出游戏
    public static final int PlayerForceExitReq = 592327; //oldVersion
    public static final int PlayerForceExitRsp = 274889; //oldVersion
    // 切换配队
    public static final int ChooseCurAvatarTeamReq = 104909; //oldVersion
    public static final int ChooseCurAvatarTeamRsp = 502224; //oldVersion
    // 添加配队容量
    public static final int AddBackupAvatarTeamReq = 653777; //oldVersion
    public static final int AddBackupAvatarTeamRsp = 983505; //oldVersion
    // 场景能力变化 例如秘境解锁方碑创造风场的风场
    public static final int SceneForceLockNotify = 217555; //oldVersion
    public static final int SceneForceUnlockNotify = 760275; //oldVersion
    // 调整时间
    public static final int SkipPlayerGameTimeReq = 899542; //oldVersion // 玩家通过esc调整时间
    public static final int SkipPlayerGameTimeRsp = 313817; //oldVersion
    public static final int ChangeGameTimeReq = 371177; //oldVersion
    public static final int ChangeGameTimeRsp = 352753; //oldVersion
    // 角色在秘境死亡
    public static final int DungeonPlayerDieReq = 807410; //oldVersion
    public static final int DungeonPlayerDieRsp = 831990; //oldVersion
    // 机关相关
    public static final int PlatformChangeRouteNotify = 303612; //oldVersion
    public static final int PlatformStartRouteNotify = 156162; //oldVersion
    public static final int PlatformStopRouteNotify = 285187; //oldVersion
    // 可能是主角切换元素
    public static final int AvatarChangeElementTypeReq = 926226; //oldVersion
    public static final int AvatarChangeElementTypeRsp = 436755; //oldVersion 单个retcode不用解
    // 联机配队
    public static final int ChangeMpTeamAvatarReq = 150034; //oldVersion
    public static final int ChangeMpTeamAvatarRsp = 746009; //oldVersion
    // 装备卸下
    public static final int TakeoffEquipReq = 545305; //oldVersion
    public static final int TakeoffEquipRsp = 451099; //oldVersion
    // 纪行
    public static final int SetBattlePassViewedReq = 543259; //oldVersion
    public static final int SetBattlePassViewedRsp = 864794; //oldVersion // 可能是 22048 533 26489 902 28919 9890 23101 21184 9036 目前实测都无效
    // 深渊
    public static final int TowerAllDataRsp = 268838; //oldVersion
    public static final int TowerCurLevelRecordChangeNotify = 805419; //oldVersion
    public static final int EnterTrialAvatarActivityDungeonReq = 590379; //oldVersion
    public static final int TowerEnterLevelReq = 469549; //oldVersion
    public static final int TowerEnterLevelRsp = 811566; //oldVersion
    public static final int TowerFloorRecordChangeNotify = 553523; //oldVersion
    public static final int TowerLevelStarCondNotify = 471604; //oldVersion
    public static final int TowerTeamSelectReq = 619063; //oldVersion
    public static final int TowerTeamSelectRsp = 786999; //oldVersion 单个retcode不用解
    public static final int DungeonRestartReq = 487994; //oldVersion
    // 神像对话
    public static final int GroupSuiteNotify = 891458; //oldVersion

    // Opcodes 5.0.0
    public static final int DelBackupAvatarTeamReq = 688709; //oldVersion
    public static final int DelBackupAvatarTeamRsp = 901705; //oldVersion
    public static final int AddQuestContentProgressReq = 778832; //oldVersion
    public static final int AddQuestContentProgressRsp = 326224; //oldVersion
    public static final int AvatarChangeCostumeNotify = 578131; //oldVersion
    public static final int AvatarEquipChangeNotify = 596564; //oldVersion
    public static final int AvatarTeamAllDataNotify = 141917; //oldVersion
    public static final int AvatarTeamUpdateNotify = 864862; //oldVersion
    public static final int ChangeAvatarReq = 481891; //oldVersion
    public static final int ChangeAvatarRsp = 639588; //oldVersion
    public static final int ClientAbilityChangeNotify = 567907; //oldVersion
    public static final int ClientAbilityInitFinishNotify = 629354; //oldVersion
    public static final int CombatInvocationsNotify = 279147; //oldVersion
    public static final int CutSceneBeginNotify = 459373; //oldVersion
    public static final int DungeonEntryInfoReq = 404081; //oldVersion
    public static final int EntityFightPropChangeReasonNotify = 993906; //oldVersion
    public static final int EntityFightPropUpdateNotify = 785011; //oldVersion
    public static final int EvtCreateGadgetNotify = 117363; //oldVersion
    public static final int EvtDoSkillSuccNotify = 453234; //oldVersion
    public static final int FinishedParentQuestNotify = 811638; //oldVersion
    public static final int FinishedParentQuestUpdateNotify = 180857; //oldVersion
    public static final int GadgetInteractReq = 639611; //oldVersion
    public static final int GadgetInteractRsp = 291458; //oldVersion
    public static final int GetPlayerFriendListReq = 168580; //oldVersion
    public static final int GetPlayerFriendListRsp = 113294; //oldVersion
    public static final int GetPlayerSocialDetailReq = 555665; //oldVersion
    public static final int GetPlayerSocialDetailRsp = 332437; //oldVersion
    public static final int HostPlayerNotify = 445079; //oldVersion
    public static final int LifeStateChangeNotify = 275101; //oldVersion
    public static final int MarkMapReq = 254623; //oldVersion
    public static final int NpcTalkReq = 410277; //oldVersion
    public static final int NpcTalkRsp = 604844; //oldVersion
    public static final int PathfindingEnterSceneReq = 811698; //oldVersion
    public static final int PlayerDataNotify = 430770; //oldVersion
    public static final int PlayerGameTimeNotify = 393906; //oldVersion
    public static final int PlayerSetPauseReq = 506553; //oldVersion
    public static final int PlayerSetPauseRsp = 623290; //oldVersion
    public static final int PlayerStoreNotify = 821950; //oldVersion
    public static final int PlayerWorldSceneInfoListNotify = 330431; //oldVersion
    public static final int PrivateChatNotify = 752325; //oldVersion
    public static final int PrivateChatReq = 121547; //oldVersion
    public static final int PullPrivateChatReq = 121549; //oldVersion
    public static final int PullPrivateChatRsp = 193230; //oldVersion
    public static final int PullRecentChatReq = 361170; //oldVersion
    public static final int PullRecentChatRsp = 500436; //oldVersion
    public static final int QuestDestroyNpcReq = 162518; //oldVersion
    public static final int QuestDestroyNpcRsp = 183009; //oldVersion
    public static final int QuestListNotify = 697057; //oldVersion
    public static final int QuestListUpdateNotify = 873190; //oldVersion
    public static final int QuestProgressUpdateNotify = 119526; //oldVersion
    public static final int SceneAreaWeatherNotify = 457448; //oldVersion
    public static final int ScenePlayerInfoNotify = 965352; //oldVersion
    public static final int SceneTimeNotify = 715496; //oldVersion
    public static final int SceneTransToPointReq = 674549; //oldVersion
    public static final int SceneTransToPointRsp = 469753; //oldVersion
    public static final int ServerTimeNotify = 117502; //oldVersion
    public static final int SetUpAvatarTeamReq = 735999; //oldVersion
    public static final int SetUpAvatarTeamRsp = 985861; //oldVersion
    public static final int SetEntityClientDataNotify = 365321; //oldVersion
    public static final int StoreItemChangeNotify = 705289; //oldVersion
    public static final int StoreWeightLimitNotify = 723724; //oldVersion
    public static final int SyncScenePlayTeamEntityNotify = 420622; //oldVersion
    public static final int SyncTeamEntityNotify = 625422; //oldVersion
    public static final int WearEquipReq = 361234; //oldVersion
    public static final int WearEquipRsp = 326425; //oldVersion
    public static final int WindSeedType1Notify = 791323; //oldVersion
    public static final int WorldDataNotify = 819996; //oldVersion
    public static final int AvatarGainCostumeNotify = 588575; //oldVersion
    public static final int PlayerQuitDungeonRsp = 150307; //oldVersion
    public static final int GetAllMailResultNotify = 486179; //oldVersion
    public static final int GetPlayerAskFriendListRsp = 238374; //oldVersion
    public static final int BattlePassAllDataNotify = 664361; //oldVersion
    public static final int EvtAvatarLockChairRsp = 953131; //oldVersion
    public static final int AvatarChangeCostumeRsp = 426797; //oldVersion
    public static final int TakeBattlePassMissionPointRsp = 418607; //oldVersion
    public static final int EvtAvatarStandUpNotify = 957232; //oldVersion
    public static final int AvatarLifeStateChangeNotify = 262964; //oldVersion
    public static final int AvatarFlycloakChangeNotify = 725813; //oldVersion
    public static final int EvtBulletHitNotify = 490299; //oldVersion
    public static final int AvatarPromoteGetRewardRsp = 262972; //oldVersion
    public static final int AvatarPropNotify = 899904; //oldVersion
    public static final int SetOpenStateRsp = 365376; //oldVersion
    public static final int RedeemLegendaryKeyRsp = 113476; //oldVersion
    public static final int BattlePassCurScheduleUpdateNotify = 947025; //oldVersion
    public static final int NormalUidOpNotify = 830290; //oldVersion
    public static final int ShowTemplateReminderNotify = 836438; //oldVersion
    public static final int SceneEntityDrownRsp = 813915; //oldVersion
    public static final int EntityAuthorityChangeNotify = 273247; //oldVersion
    public static final int PlayerTimeNotify = 781153; //oldVersion
    public static final int QuestUpdateQuestVarNotify = 752483; //oldVersion
    public static final int ServerGlobalValueChangeNotify = 523109; //oldVersion
    public static final int GetInvestigationMonsterRsp = 338797; //oldVersion
    public static final int AvatarDieAnimationEndReq = 519023; //oldVersion
    public static final int AvatarDieAnimationEndRsp = 398191; //oldVersion
    public static final int SetNameCardReq = 213874; //oldVersion
    public static final int SetNameCardRsp = 162674; //oldVersion
    public static final int SetPlayerNameReq = 310134; //oldVersion
    public static final int SetPlayerNameRsp = 533371; //oldVersion
    public static final int SetPlayerSignatureReq = 353148; //oldVersion
    public static final int SetPlayerSignatureRsp = 746369; //oldVersion
    public static final int PersonalSceneJumpReq = 494472; //oldVersion
    public static final int GetProfilePictureDataReq = 179086; //oldVersion
    public static final int GetProfilePictureDataRsp = 484239; //oldVersion
    public static final int ProfilePictureUpdateNotify = 879509; //oldVersion
    public static final int SetPlayerHeadImageReq = 107415; //oldVersion
    public static final int SetPlayerHeadImageRsp = 783255; //oldVersion
    public static final int GetAllUnlockNameCardReq = 953244; //oldVersion
    public static final int GetAllUnlockNameCardRsp = 140189; //oldVersion
    public static final int SetPlayerBirthdayReq = 719773; //oldVersion
    public static final int SetPlayerBirthdayRsp = 646047; //oldVersion
    public static final int GalleryWillStartCountdownNotify = 230305; //oldVersion
    public static final int GetWidgetSlotRsp = 562083; //oldVersion
    public static final int AvatarExpeditionDataNotify = 248740; //oldVersion
    public static final int BattlePassChangeRewardPlanReq = 924580; //oldVersion
    public static final int BattlePassChangeRewardPlanRsp = 738218; //oldVersion
    public static final int BattlePassMissionUpdateNotify = 402347; //oldVersion
    public static final int GetParentQuestVideoKeyReq = 263083; //oldVersion
    public static final int GetParentQuestVideoKeyRsp = 463789; //oldVersion
    public static final int VehicleStaminaNotify = 592815; //oldVersion
    public static final int ServerBuffChangeNotify = 717745; //oldVersion
    public static final int VehicleInteractReq = 189363; //oldVersion
    public static final int VehicleInteractRsp = 846774; //oldVersion
    public static final int ScenePlayerLocationNotify = 777146; //oldVersion
    public static final int PlayerPropChangeNotify = 803771; //oldVersion
    public static final int PlayerPropChangeReasonNotify = 924605; //oldVersion
    public static final int PlayerPropNotify = 822208; //oldVersion
    public static final int GetDailyDungeonEntryInfoRsp = 738242; //oldVersion
    public static final int DungeonPreloadMonsterNotify = 873413; //oldVersion
    public static final int RegionSearchNotify = 304071; //oldVersion
    public static final int EffigyChallengeV4PrepareNotify = 547784; //oldVersion
    public static final int GetCityHuntingOfferRsp = 150472; //oldVersion
    public static final int GMShowNavMeshRsp = 205776; //oldVersion
    public static final int DealAddFriendRsp = 826328; //oldVersion
    public static final int CodexDataUpdateNotify = 525279; //oldVersion
    public static final int FishBattleEndRsp = 218082; //oldVersion
    public static final int GetUgcDungeonBriefListRsp = 672739; //oldVersion // proto
    public static final int AchievementAllDataNotify = 150504; //oldVersion
    public static final int HideAndSeekSelectAvatarRsp = 293866; //oldVersion
    public static final int ChapterStateNotify = 179180; //oldVersion
    public static final int DataResVersionNotify = 259053; //oldVersion
    public static final int GCGReplayAskDuelRsp = 674799; //oldVersion // proto
    public static final int GetCustomDungeonRsp = 996339; //oldVersion // proto
    public static final int IslandPartySailInfoNotify = 705533; //oldVersion // proto
    public static final int MarkMapRsp = 814078; //oldVersion
    public static final int OtherPlayerEnterHomeNotify = 128004; //oldVersion
    public static final int SalvagePreventSettleNotify = 615438; //oldVersion // proto
    public static final int SceneEntitiesMovesRsp = 199695; //oldVersion // proto
    public static final int GetActivityInfoReq = 148496; //oldVersion
    public static final int GetActivityInfoRsp = 930837; //oldVersion
    public static final int ChatChannelUpdateNotify = 603159; //oldVersion // proto
    public static final int ChatChannelInfoNotify = 676888; //oldVersion // proto
    public static final int PlayerChatNotify = 664605; //oldVersion
    public static final int SetWidgetSlotReq = 689184; //oldVersion
    public static final int SetWidgetSlotRsp = 904225; //oldVersion
    public static final int WidgetSlotChangeNotify = 177185; //oldVersion
    public static final int CreateVehicleReq = 115752; //oldVersion
    public static final int CreateVehicleRsp = 406569; //oldVersion
    public static final int DungeonEntryInfoRsp = 756778; //oldVersion
    public static final int PlayerEnterDungeonReq = 785451; //oldVersion
    public static final int PlayerEnterDungeonRsp = 125996; //oldVersion
    public static final int PlayerQuitDungeonReq = 576558; //oldVersion
    public static final int SelectWorktopOptionReq = 627771; //oldVersion
    public static final int SelectWorktopOptionRsp = 277565; //oldVersion
    public static final int UseItemReq = 209985; //oldVersion
    public static final int UseItemRsp = 654404; //oldVersion
    public static final int EvtAiSyncSkillCdNotify = 242760; //oldVersion
    public static final int DungeonChallengeBeginNotify = 988233; //oldVersion
    public static final int ChallengeDataNotify = 506958; //oldVersion
    public static final int GetCityReputationInfoReq = 212050; //oldVersion // code
    public static final int GetCityReputationInfoRsp = 334931; //oldVersion // code
    public static final int GetTribeReputationInfoReq = 926806; //oldVersion // code
    public static final int GetTribeReputationInfoRsp = 310361; //oldVersion // code
    public static final int WorktopOptionNotify = 300127; //oldVersion
    public static final int GadgetStateNotify = 228450; //oldVersion
    public static final int DungeonChallengeFinishNotify = 377955; //oldVersion
    public static final int ToTheMoonEnterSceneRsp = 242786; //oldVersion
    public static final int WorldPlayerDieNotify = 801891; //oldVersion
    public static final int WorldPlayerReviveReq = 470122; //oldVersion
    public static final int WorldPlayerReviveRsp = 726127; //oldVersion
    public static final int EntityPropNotify = 953457; //oldVersion
    public static final int GetFriendShowAvatarInfoRsp = 644214; //oldVersion
    public static final int GetPlayerBlacklistReq = 908407; //oldVersion
    public static final int GetPlayerAskFriendListReq = 398455; //oldVersion
    public static final int GetPlayerBlacklistRsp = 601209; //oldVersion
    public static final int GetPlayerMpModeAvailabilityRsp = 185468; //oldVersion
    public static final int UpdatePlayerShowAvatarListReq = 808065; //oldVersion
    public static final int UpdatePlayerShowAvatarListRsp = 396417; //oldVersion
    public static final int UpdatePlayerShowNameCardListReq = 103554; //oldVersion
    public static final int UpdatePlayerShowNameCardListRsp = 117892; //oldVersion
    public static final int AvatarFetterDataNotify = 228485; //oldVersion
    public static final int WidgetDoBagReq = 212101; //oldVersion
    public static final int WidgetDoBagRsp = 648325; //oldVersion
    public static final int WidgetGadgetAllDataNotify = 969861; //oldVersion
    public static final int WidgetGadgetDataNotify = 885901; //oldVersion
    public static final int HomeChooseModuleReq = 371853; //oldVersion
    public static final int HomeChooseModuleRsp = 334993; //oldVersion
    public static final int TryEnterHomeReq = 902289; //oldVersion
    public static final int TryEnterHomeRsp = 119959; //oldVersion
    public static final int HomeBasicInfoNotify = 214171; //oldVersion
    public static final int HomeLimitedShopInfoNotify = 685214; //oldVersion
    public static final int PlayerQuitFromHomeNotify = 560287; //oldVersion
    public static final int AllMarkPointNotify = 935073; //oldVersion
    public static final int BatchDelMapMarkReq = 611489; //oldVersion // code
    public static final int BatchDelMapMarkRsp = 896163; //oldVersion // code
    public static final int HomeModuleSeenReq = 861348; //oldVersion
    public static final int HomeModuleSeenRsp = 216225; //oldVersion
    public static final int ItemAddHintNotify = 599206; //oldVersion
    public static final int PlayerHomeCompInfoNotify = 320677; //oldVersion
    public static final int GetAreaExplorePointReq = 380084; //oldVersion // code
    public static final int GetAreaExplorePointRsp = 584884; //oldVersion // code
    public static final int HomeComfortInfoNotify = 883894; //oldVersion
    public static final int HomeModuleUnlockNotify = 920764; //oldVersion
    public static final int FurnitureCurModuleArrangeCountNotify = 130236; //oldVersion
    public static final int HomeMarkPointNotify = 163005; //oldVersion
    public static final int HomeAllUnlockedBgmIdListNotify = 691393; //oldVersion
    public static final int HomeAvatarAllFinishRewardNotify = 769218; //oldVersion
    public static final int HomeGetBasicInfoReq = 335051; //oldVersion
    public static final int HomePreChangeEditModeNotify = 806092; //oldVersion
    public static final int HomeChangeEditModeReq = 578767; //oldVersion
    public static final int HomeChangeEditModeRsp = 773328; //oldVersion
    public static final int HomeEnterEditModeFinishReq = 646352; //oldVersion
    public static final int HomeEnterEditModeFinishRsp = 191698; //oldVersion
    public static final int HomeChangeBgmNotify = 902358; //oldVersion
    public static final int HomeChangeBgmReq = 978136; //oldVersion
    public static final int HomeGetArrangementInfoReq = 177374; //oldVersion
    public static final int HomeGetArrangementInfoRsp = 826591; //oldVersion
    public static final int HomeUpdateArrangementInfoRsp = 441568; //oldVersion
    public static final int HomeUpdateArrangementInfoReq = 402657; //oldVersion
    public static final int GetShopReq = 679138; //oldVersion
    public static final int GetShopRsp = 300255; //oldVersion // ShopGoods proto
    public static final int ActivityScheduleInfoNotify = 105700; //oldVersion
    public static final int GetActivityScheduleRsp = 126183; //oldVersion
    public static final int PersonalLineAllDataReq = 873705; //oldVersion
    public static final int CodexDataFullNotify = 341230; //oldVersion // proto
    public static final int PlayerMatchSuccNotify = 732403; //oldVersion // proto
    public static final int SalvageEscortSettleNotify = 353532; //oldVersion // proto
    public static final int UgcDungeonPlayRecordNotify = 255228; //oldVersion // proto
    public static final int ViewCodexRsp = 361726; //oldVersion // proto
    public static final int SaveUgcRsp = 136449; //oldVersion // proto
    public static final int ActivityInfoNotify = 367880; //oldVersion
    public static final int HomeAvatarSummonAllEventNotify = 539913; //oldVersion
    public static final int HomeAvatarSummonEventReq = 181522; //oldVersion
    public static final int HomeAvatarRewardEventNotify = 322839; //oldVersion
    public static final int HomeAvatarTalkFinishInfoNotify = 830746; //oldVersion
    public static final int HomeAvatarTalkRsp = 150810; //oldVersion
    public static final int HomeSceneJumpReq = 277793; //oldVersion
    public static final int HomeSceneJumpRsp = 101668; //oldVersion
    public static final int HomeTransferReq = 462120; //oldVersion
    public static final int GetInvestigationMonsterReq = 656686; //oldVersion // proto
    public static final int GetHomeLevelUpRewardReq = 525618; //oldVersion // proto
    public static final int HomeAvatarRewardEventGetReq = 849202; //oldVersion
    public static final int HomeAvatarRewardEventGetRsp = 464180; //oldVersion
    public static final int GetAllMailNotify = 681268; //oldVersion
    public static final int GetGachaInfoReq = 656693; //oldVersion
    public static final int GetGachaInfoRsp = 859445; //oldVersion
    public static final int DoGachaReq = 126264; //oldVersion
    public static final int DoGachaRsp = 253242; //oldVersion
    public static final int AvatarChangeCostumeReq = 466236; //oldVersion
    public static final int HomeAvatarCostumeChangeNotify = 646462; //oldVersion
    public static final int AvatarWearFlycloakReq = 273732; //oldVersion
    public static final int AvatarWearFlycloakRsp = 988490; //oldVersion
    public static final int AvatarGainFlycloakNotify = 527690; //oldVersion
    public static final int AvatarChangeTraceEffectReq = 382285; //oldVersion
    public static final int PlayerApplyEnterMpResultNotify = 607568; //oldVersion
    public static final int GetOnlinePlayerInfoRsp = 871762; //oldVersion
    public static final int PlayerApplyEnterMpNotify = 531795; //oldVersion
    public static final int PlayerApplyEnterMpReq = 793942; //oldVersion
    public static final int PlayerApplyEnterMpRsp = 509272; //oldVersion
    public static final int PlayerApplyEnterMpResultReq = 222553; //oldVersion
    public static final int PlayerApplyEnterMpAfterMatchAgreedNotify = 351578; //oldVersion
    public static final int DeathZoneInfoNotify = 220508; //oldVersion
    public static final int AddFriendNotify = 841055; //oldVersion
    public static final int AskAddFriendNotify = 318815; //oldVersion
    public static final int AskAddFriendReq = 996705; //oldVersion
    public static final int DealAddFriendReq = 603492; //oldVersion
    public static final int SetFriendRemarkNameReq = 851302; //oldVersion
    public static final int SetFriendRemarkNameRsp = 705896; //oldVersion
    public static final int GetFriendShowAvatarInfoReq = 834922; //oldVersion
    public static final int GetFriendShowNameCardInfoRsp = 234859; //oldVersion
    public static final int SetFriendEnterHomeOptionReq = 857451; //oldVersion
    public static final int GetOnlinePlayerListReq = 372079; //oldVersion
    public static final int GetOnlinePlayerListRsp = 529776; //oldVersion
    public static final int SetPlayerPropReq = 834928; //oldVersion
    public static final int GetShopmallDataReq = 218484; //oldVersion
    public static final int GetActivityShopSheetInfoReq = 771447; //oldVersion // proto
    public static final int GetActivityShopSheetInfoRsp = 370044; //oldVersion // proto
    public static final int ServerAnnounceNotify = 982399; //oldVersion // proto
    public static final int EvtDestroyGadgetNotify = 722304; //oldVersion // proto
    public static final int ChangeWorldToSingleModeRsp = 253312; //oldVersion // proto
    public static final int GetWorldMpInfoReq = 806274; //oldVersion // proto
    public static final int GetWorldMpInfoRsp = 998791; //oldVersion // proto
    public static final int GetWidgetSlotReq = 861576; //oldVersion
    public static final int HomeSaveBlueprintToSlotRsp = 888204; //oldVersion // proto
    public static final int HomeGetBlueprintSlotInfoReq = 406930; //oldVersion // proto
    public static final int HomeGetBlueprintSlotInfoRsp = 765333; //oldVersion // proto
    public static final int HomeCreateBlueprintRsp = 202136; //oldVersion // proto
    public static final int WorldPlayerLocationNotify = 343456; //oldVersion
    public static final int ResinChangeNotify = 515488; //oldVersion
    public static final int GetAllMailReq = 699809; //oldVersion
    public static final int GetAllMailRsp = 232867; //oldVersion
    public static final int GetMailItemReq = 748960; //oldVersion
    public static final int GetMailItemRsp = 894369; //oldVersion
    public static final int MailChangeNotify = 894368; //oldVersion
    public static final int ReadMailNotify = 933280; //oldVersion
    public static final int ChangeMailStarNotify = 603560; //oldVersion
    public static final int DelMailReq = 990624; //oldVersion
    public static final int DelMailRsp = 589227; //oldVersion
    public static final int HitTreeNotify = 732592; //oldVersion
    public static final int TheaterLobbySceneJumpReq = 761271; //oldVersion // code
    public static final int TheaterLobbySceneJumpRsp = 583098; //oldVersion // code
    public static final int EvtAvatarLockChairReq = 245184; //oldVersion
    public static final int ObstacleModifyNotify = 372166; //oldVersion
    public static final int SetOpenStateReq = 808390; //oldVersion
    public static final int GetMapMarkTipsReq = 822730; //oldVersion // proto
    public static final int GetMapMarkTipsRsp = 828875; //oldVersion // proto
    public static final int GetCityReputationMapInfoReq = 445904; //oldVersion // proto
    public static final int GetCityReputationMapInfoRsp = 450000; //oldVersion // proto
    public static final int GetMapAreaReq = 323025; //oldVersion
    public static final int GetMapAreaRsp = 591316; //oldVersion
    public static final int GetQuestLackingResourceReq = 376282; //oldVersion
    public static final int PlayerOfferingDataNotify = 851425; //oldVersion // proto
    public static final int PlayerOfferingReq = 867810; //oldVersion // proto
    public static final int PlayerOfferingRsp = 161249; //oldVersion // proto
    public static final int OfferingInteractReq = 558564; //oldVersion // proto
    public static final int OfferingInteractRsp = 667109; //oldVersion // proto
    public static final int EnterWorldAreaReq = 181733; //oldVersion
    public static final int EnterWorldAreaRsp = 261608; //oldVersion
    public static final int AbilityChangeNotify = 138737; //oldVersion
    public static final int SceneAreaUnlockNotify = 554493; //oldVersion
    public static final int UnfreezeGroupLimitNotify = 124418; //oldVersion
    public static final int MapAreaChangeNotify = 624134; //oldVersion
    public static final int QueryCodexMonsterBeKilledNumReq = 210438; //oldVersion // proto
    public static final int QueryCodexMonsterBeKilledNumRsp = 177674; //oldVersion // proto
    public static final int GetRegionSearchReq = 321043; //oldVersion
    public static final int GetHomeExchangeWoodInfoReq = 933396; //oldVersion
    public static final int PlayerChatReq = 282137; //oldVersion
    public static final int GetWidgetQuickSlotListReq = 443934; //oldVersion
    public static final int TowerAllDataReq = 470559; //oldVersion
    public static final int GetAllSceneGalleryInfoReq = 919074; //oldVersion // proto
    public static final int GetPlayerHomeCompInfoReq = 103976; //oldVersion
    public static final int GetFurnitureCurModuleArrangeCountReq = 902696; //oldVersion
    public static final int FurnitureMakeReq = 693800; //oldVersion
    public static final int OfferingPariSearchFinishNotify = 529964; //oldVersion // proto
    public static final int OfferingPariSearchReq = 710189; //oldVersion // proto
    public static final int OfferingPariSearchResultNotify = 591412; //oldVersion // proto
    public static final int OfferingPariSearchRsp = 462391; //oldVersion // proto
    public static final int OfferingPariTakeFinishRewardReq = 132663; //oldVersion // proto
    public static final int OfferingPariTakeFinishRewardRsp = 906811; //oldVersion // proto
    public static final int TakeOfferingLevelRewardReq = 646717; //oldVersion // proto
    public static final int TakeOfferingLevelRewardRsp = 759358; //oldVersion // proto
    public static final int ScenePointUnlockNotify = 919103; //oldVersion
    public static final int OpenBlossomCircleCampGuideNotify = 241222; //oldVersion
    public static final int DungeonPlayerDieNotify = 675402; //oldVersion
    public static final int DungeonDieOptionReq = 106060; //oldVersion
    public static final int DungeonDieOptionRsp = 783951; //oldVersion
    public static final int ChangeTeamNameReq = 720465; //oldVersion
    public static final int ChangeTeamNameRsp = 140883; //oldVersion
    public static final int AbilityInvocationsNotify = 755286; //oldVersion
    public static final int WorldPlayerRTTNotify = 853591; //oldVersion
    public static final int PlayerApplyEnterMpResultRsp = 577112; //oldVersion
    public static final int PlayerGetForceQuitBanInfoRsp = 702049; //oldVersion
    public static final int PlayerPreEnterMpNotify = 495206; //oldVersion
    public static final int WorldPlayerInfoNotify = 527977; //oldVersion
    public static final int WeaponAwakenReq = 650857; //oldVersion
    public static final int WeaponAwakenRsp = 353905; //oldVersion
    public static final int WeaponPromoteReq = 370290; //oldVersion
    public static final int WeaponPromoteRsp = 824951; //oldVersion
    public static final int WeaponUpgradeReq = 740985; //oldVersion
    public static final int WeaponUpgradeRsp = 472701; //oldVersion
    public static final int CalcWeaponUpgradeReturnItemsReq = 974462; //oldVersion
    public static final int CalcWeaponUpgradeReturnItemsRsp = 310910; //oldVersion
    public static final int SetEquipLockStateReq = 540287; //oldVersion
    public static final int SetEquipLockStateRsp = 349822; //oldVersion
    public static final int AvatarUpgradeReq = 464516; //oldVersion
    public static final int AvatarUpgradeRsp = 190085; //oldVersion
    public static final int AvatarSkillUpgradeReq = 374404; //oldVersion
    public static final int AvatarSkillUpgradeRsp = 822920; //oldVersion
    public static final int AvatarUnlockTalentNotify = 269963; //oldVersion
    public static final int HomeAvatarTalkReq = 980621; //oldVersion
    public static final int GetQuestLackingResourceRsp = 142990; //oldVersion
    public static final int QueryPathReq = 519830; //oldVersion
    public static final int QueryPathRsp = 491162; //oldVersion
    public static final int UnlockTransPointReq = 644764; //oldVersion
    public static final int UnlockTransPointRsp = 198311; //oldVersion


    // Packet Names
    public static final int PlayerEnterChildMapLayerNotify = 929451; //oldVersion 没有作用
    public static final int PlayerEnterMapLayerNotify = 915119; //oldVersion 没有作用
    public static final int ServerAnnounceRevokeNotify = 804530; //oldVersion 没有作用
    public static final int PlayerChatRsp = 661174; //oldVersion 可以忽略
    public static final int FurnitureMakeRsp = 585415; //oldVersion

    public static final int ActivityTakeWatcherRewardReq = 487120; //oldVersion
    public static final int ActivityTakeWatcherRewardRsp = 224976; //oldVersion
    public static final int ActivityUpdateWatcherNotify = 126676; //oldVersion
    public static final int AllWidgetDataNotify = 188117; //oldVersion todo proto需要的东西太多 先不搞
    // 可能是角色派遣
    public static final int AvatarExpeditionAllDataReq = 782041; //oldVersion
    public static final int AvatarExpeditionAllDataRsp = 405212; //oldVersion
    public static final int AvatarExpeditionCallBackReq = 646881; //oldVersion
    public static final int AvatarExpeditionCallBackRsp = 605925; //oldVersion
    public static final int AvatarExpeditionGetRewardReq = 100070; //oldVersion
    public static final int AvatarExpeditionGetRewardRsp = 816872; //oldVersion
    public static final int AvatarExpeditionStartReq = 671474; //oldVersion
    public static final int AvatarExpeditionStartRsp = 474872; //oldVersion

    public static final int BargainOfferPriceReq = 964345; //oldVersion
    public static final int BargainOfferPriceRsp = 603897; //oldVersion
    public static final int BargainStartNotify = 653050; //oldVersion
    public static final int BargainTerminateNotify = 839420; //oldVersion
    public static final int BeginCameraSceneLookNotify = 229117; //oldVersion 太难了先不解
    public static final int BuyBattlePassLevelReq = 157433; //oldVersion todo 纪行有关？
    public static final int BuyBattlePassLevelRsp = 694016; //oldVersion

    public static final int CanUseSkillNotify = 298760; //oldVersion 不好解
    public static final int CancelCoopTaskReq = 220937; //oldVersion 未实现的数据包
    // todo 上面的可以不解
    public static final int CheckUgcStateReq = 472841; //oldVersion
    public static final int CheckUgcStateRsp = 960266; //oldVersion
    public static final int CheckUgcUpdateReq = 378638; //oldVersion
    public static final int CheckUgcUpdateRsp = 399118; //oldVersion
    public static final int ClientLockGameTimeNotify = 571152; //oldVersion 我觉得不用解
    public static final int CloseCommonTipsNotify = 493331; //oldVersion 不好解
    public static final int CombineDataNotify = 550676; //oldVersion 不好解

    public static final int CookDataNotify = 501525; //oldVersion todo
    public static final int CookRecipeDataNotify = 747285; //oldVersion

    public static final int DeleteFriendNotify = 425752; //oldVersion 等待抓取
    public static final int DeleteFriendReq = 317212; //oldVersion
    public static final int DeleteFriendRsp = 726818; //oldVersion

    public static final int DungeonShowReminderNotify = 802599; //oldVersion 不好解
    public static final int DungeonSlipRevivePointActivateReq = 630572; //oldVersion 不好解
    public static final int DungeonSlipRevivePointActivateRsp = 636721; //oldVersion 不好解
    public static final int DungeonWayPointActivateReq = 945970; //oldVersion 不好解
    public static final int DungeonWayPointActivateRsp = 962356; //oldVersion 不好解

    public static final int EndCameraSceneLookNotify = 669494; //oldVersion 等待抓取

    public static final int EntityAiKillSelfNotify = 249656; //oldVersion 不好解

    public static final int EvtBulletDeactiveNotify = 292666; //oldVersion 懒得解了反正解不解都没事
    public static final int EvtBulletMoveNotify = 882492; //oldVersion 懒得解了反正解不解都没事

    public static final int FireworksLaunchDataNotify = 444224; //oldVersion 套娃太多了 todo
    public static final int FireworksReformDataNotify = 153408; //oldVersion 套娃太多了 todo

    public static final int ForgeGetQueueDataReq = 104258; //oldVersion 等待抓取
    public static final int ForgeQueueManipulateReq = 624451; //oldVersion
    public static final int ForgeQueueManipulateRsp = 657226; //oldVersion 疑似结构改变

    public static final int FurnitureMakeStartReq = 880459; //oldVersion

    public static final int GetAllActivatedBargainDataReq = 122699; //oldVersion 等待抓取
    public static final int GetAllActivatedBargainDataRsp = 161616; //oldVersion

    public static final int GetAllH5ActivityInfoReq = 628569; //oldVersion 等待抓取

    public static final int GetBargainDataReq = 567133; //oldVersion 不好解
    public static final int GetBargainDataRsp = 599905; //oldVersion

    public static final int GetChatEmojiCollectionReq = 341860; //oldVersion 等待抓取
    public static final int GetChatEmojiCollectionRsp = 718696; //oldVersion 不好解

    public static final int GetDungeonEntryExploreConditionRsp = 640872; //oldVersion 不好解 todo
    public static final int GetFriendShowNameCardInfoReq = 298862; //oldVersion 等待抓取
    public static final int GetHomeLevelUpRewardRsp = 681840; //oldVersion 不好解
    public static final int GetUgcBriefInfoReq = 878448; //oldVersion 跳过
    public static final int GetUgcBriefInfoRsp = 497522; //oldVersion 跳过
    public static final int GetUgcReq = 653173; //oldVersion
    public static final int GetUgcRsp = 241527; //oldVersion

    public static final int GmTalkReq = 987004; //oldVersion 等待抓取
    public static final int GroupUnloadNotify = 462721; //oldVersion 不好解
    public static final int H5ActivityIdsNotify = 626564; //oldVersion 等待抓取

    // 家园
    public static final int HomeAvatarSummonEventRsp = 927622; //oldVersion
    public static final int HomeAvatarSummonFinishReq = 847758; //oldVersion
    public static final int HomeAvatarSummonFinishRsp = 225167; //oldVersion
    public static final int HomeChangeBgmRsp = 219023; //oldVersion
    public static final int HomeChangeModuleReq = 888719; //oldVersion
    public static final int HomeChangeModuleRsp = 464792; //oldVersion
    public static final int HomeGetOnlineStatusReq = 935833; //oldVersion
    public static final int HomeGetOnlineStatusRsp = 493466; //oldVersion
    public static final int HomeKickPlayerReq = 325529; //oldVersion
    public static final int HomeKickPlayerRsp = 356252; //oldVersion
    public static final int HomeNewUnlockedBgmIdListNotify = 999329; //oldVersion
    public static final int HomeResourceNotify = 524194; //oldVersion
    public static final int HomeResourceTakeFetterExpReq = 511921; //oldVersion
    public static final int HomeResourceTakeFetterExpRsp = 376755; //oldVersion
    public static final int HomeResourceTakeHomeCoinReq = 120755; //oldVersion
    public static final int HomeResourceTakeHomeCoinRsp = 171958; //oldVersion
    public static final int HomeSaveArrangementNoChangeReq = 831420; //oldVersion
    public static final int HomeSaveArrangementNoChangeRsp = 442301; //oldVersion
    public static final int HomeSceneInitFinishReq = 659390; //oldVersion
    public static final int HomeSceneInitFinishRsp = 387008; //oldVersion
    public static final int HomeTransferRsp = 384966; //oldVersion

    // 好像用不到这俩了
    public static final int ItemGivingReq = 661454; //oldVersion
    public static final int ItemGivingRsp = 135119; //oldVersion

    public static final int LaunchFireworksReq = 258000; //oldVersion 不好解
    public static final int LaunchFireworksRsp = 262095; //oldVersion 单个retcode 不用解

    public static final int ServerCondMeetQuestListUpdateNotify = 673752; //oldVersion 不好解
    public static final int MarkNewNotify = 632793; //oldVersion 不好解
    public static final int MonsterForceAlertNotify = 399322; //oldVersion 不好解
    public static final int PlayerLevelRewardUpdateNotify = 286683; //oldVersion 不好解
    public static final int QuickUseWidgetReq = 714716; //oldVersion 太麻烦了 以后再补
    public static final int QuickUseWidgetRsp = 683996; //oldVersion
    public static final int ReformFireworksReq = 647134; //oldVersion 太麻烦了 先不搞
    public static final int ReformFireworksRsp = 364513; //oldVersion 单个retcode 不用解
    public static final int SceneEntityDrownReq = 733153; //oldVersion 不好解
    public static final int SetChatEmojiCollectionReq = 989155; //oldVersion 不好解 而且看起来没什么用 跳过
    public static final int SetChatEmojiCollectionRsp = 782309; //oldVersion 单个retcode不用解

    public static final int SetFriendEnterHomeOptionRsp = 872429; //oldVersion 单个retcode 不用解
    public static final int SetPlayerPropRsp = 614383; //oldVersion 单个retcode不用解

    public static final int SetUpLunchBoxWidgetReq = 389103; //oldVersion 不好解
    public static final int SetUpLunchBoxWidgetRsp = 251889; //oldVersion
    public static final int ShowClientGuideNotify = 755699; //oldVersion 不好解
    public static final int TowerMiddleLevelChangeTeamNotify = 329718; //oldVersion 待抓取
    public static final int UnlockedFurnitureFormulaDataNotify = 448505; //oldVersion 不好解
    public static final int UnlockedFurnitureSuiteDataNotify = 946171; //oldVersion 不好解
}

